# Generated by Django 4.2.6 on 2023-11-16 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ki.models


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0004_auto_20231016_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='sidik_jari_image',
            field=models.ImageField(upload_to='biometric_data/', validators=[ki.models.validate_video_file]),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='tanggal_lahir',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='umur',
            field=models.CharField(max_length=2),
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('symmetric_key', models.BinaryField(blank=True, null=True)),
                ('encrypted_symmetric_key', models.BinaryField(blank=True, null=True)),
                ('requested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to=settings.AUTH_USER_MODEL)),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
